#ifndef __HDFM_TUNER_TUNER_SRC_MAIN_CPP_CONFIG_H__
#define __HDFM_TUNER_TUNER_SRC_MAIN_CPP_CONFIG_H__

#define HAVE_FAAD2
#define USE_FAAD2
#define USE_THREADS
#define USE_COLOR

#define HAVE_PTHREAD_SETNAME_NP
#define HAVE_STRNDUP
#define HAVE_CMPLXF

#endif
